greeting = "hello"
name=input("enter name?")
print(greeting + name)
age=input("enter your age ?")
print( age ,"that's a good age for you to learn more " )
game=input("what is your favourit game?")
print( game ,"is a good game ")
school=input("which school do you attend?")
print(school,"sounds good")
dreamCountry=input("what is your dream country ")
print(dreamCountry,"sounds good")
print("bye" ,name)